build.sbt
project/plugins.sbt
sbt-java-gen/src/main/scala/Fs2GrpcPlugin.scala

This uses sbt-buildinfo to get the version information from SBT and inject it into the SBT plugin.

SBT plugin should add library dependency of corresponding runtime.

---

sbt-java-gen/src/main/scala/GrpcServicePrinter.scala

Removes the hard coded `GreeterGrcp` name and uses the ServiceDescriptor to discover the proper name.

fixes package path and naming in client generation code

---

sbt-java-gen/src/main/scala/Fs2GrpcPlugin.scala
sbt-java-gen/src/main/scala/GrpcServicePrinter.scala

Some of these features wrap around scalapb's plugin, offering a more
SBT-ish API.
Two AutoPlugins:
- Fs2GrpcPlugin (enabled by default) with three settings (w/ useful defaults)
scalapbCodeGeneratorOptions - Settings for code generation
scalapbProtobufDirectory - Directory containing protocol buffer files
scalapbCodeGenerators - Code generators for scalapb and fs2-grpc
- Fs2Grpc (enabled on demand)
Sets PB.targets to point at the values from scalapbCodeGenerators
Example project after this:
```scala
lazy val protobuf =
project
.in(file("."))
.enablePlugins(Fs2Grpc)
.settings(
scalapbCodeGeneratorOptions += CodeGeneratorOption.FlatPackage
)
```

Updated SBT plugin API and features

---

build.sbt
project/build.properties
project/plugins.sbt

scalapb       0.7.1 -> 0.7.2
cats-effect   0.10  -> 0.10.1
sbt-buildinfo 0.8.0 -> 0.9.0
sbt           1.1.2 -> 1.1.4
Removes unneeded protoc/etc. from build.

Bump library versions, remove unused build dependencies.

---

build.sbt
project/plugins.sbt

Add MiMa to build to check for binary issues (currently comparing with 0.3.0).

Add MiMa to build.

---

.travis.yml

Adds Oracle JDK 10 to build matrix, updates to scala 2.12.6

Update Travis versions (scala and JDK updates)

---

build.sbt

This isn't needed for generating code, just for running it.

Remove grpc-core dependency from SBT generator plugin

---

project/plugins.sbt
sbt-java-gen/src/main/scala/Fs2GrpcPlugin.scala
sbt-java-gen/src/main/scala/GrpcServicePrinter.scala

- upgrade to ScalaPB 0.8.0
- adjust `Fs2GrpcPlugin` and `GrpcServicePrinter` to
changes done with respect to `DescriptorImplicits`
class that previously was trait `DescriptorPimps`.

scalapb upgrade

---

.travis.yml
build.sbt
java-runtime/src/main/scala/client/Fs2ClientCall.scala
java-runtime/src/main/scala/client/Fs2StreamClientCallListener.scala
java-runtime/src/main/scala/client/Fs2UnaryClientCallListener.scala
java-runtime/src/main/scala/implicits.scala
java-runtime/src/main/scala/java_runtime.scala
java-runtime/src/main/scala/server/Fs2ServerCall.scala
java-runtime/src/main/scala/server/Fs2ServerCallHandler.scala
java-runtime/src/main/scala/server/Fs2ServerCallListener.scala
java-runtime/src/main/scala/server/Fs2StreamServerCallListener.scala
java-runtime/src/main/scala/server/Fs2UnaryServerCallListener.scala
java-runtime/src/main/scala/syntax/AllSyntax.scala
java-runtime/src/main/scala/syntax/ManagedChannelBuilderSyntax.scala
java-runtime/src/main/scala/syntax/ServerBuilderSyntax.scala
java-runtime/src/main/scala/syntax/package.scala
java-runtime/src/test/scala/client/ClientSuite.scala
java-runtime/src/test/scala/client/DummyClientCall.scala
java-runtime/src/test/scala/server/ServerSuite.scala
project/build.properties
project/plugins.sbt
sbt-java-gen/src/main/scala/GrpcServicePrinter.scala

- adjust client and server based code to operate
in terms of type classes instead of `IO`.
- fix server suite tests that were commented.
- adjust grpc service printer to use fs2 1.0 based
code.
- make grpc service printer easier to read by introducing
constants for common types used in signatures.
- change travis from oraclejdk10 to openjdk11 and
bump scala.
- add sbt-coursier for faster artifact fetching
- upgrade dependencies.

fs2 1.0: adjustments to runtime & codegen

---

java-runtime/src/main/scala/client/Fs2ClientCall.scala
java-runtime/src/main/scala/server/Fs2ServerCallListener.scala
java-runtime/src/main/scala/server/Fs2StreamServerCallListener.scala
java-runtime/src/main/scala/server/Fs2UnaryServerCallListener.scala
java-runtime/src/test/scala/client/ClientSuite.scala
java-runtime/src/test/scala/client/DummyClientCall.scala
java-runtime/src/test/scala/server/DummyServerCall.scala
java-runtime/src/test/scala/server/ServerSuite.scala

- If client call is cancelled, it will send a cancellation message to the server
- If client processing fails while streaming, it will send a cancellation
message to the server
- If cancellation is signalled, Server will attempt to cancel ongoing processing
(via effect cancelation), and respond with status CANCELLED.
Fixes #4

Cancellation support for cats-effect

---

README.md

Got burnt by `value resource is not a member of ?0` when I didn't have it.

Add missing implicits import to server sample code

---

sbt-java-gen/src/main/scala/Fs2GrpcPlugin.scala

- fix missing file descriptors. The list of
file descriptors handed to `DescriptorImplicits`
should come from `getProtoFileList` and not
`getFileToGenerateList` as a service might use
types that are not generated.
Note: This is the same approach that ScalaPB itself
uses when populating `DescriptorImplicits` with
file descriptors.

generator: fix missing file descriptors

---

.travis.yml
build.sbt
project/Dependencies.scala
project/plugins.sbt

- set 2.13.0 as default version.
- upgrade fs2, cats-effect, minitest and ScalaPB.
- add `Dependencies` project file to keep versions
and dependencies separated from build.sbt
- adjust travis to account for 2.13.0.
- upgrade sbt-tpolecat to get 2.13.0 support.

dependencies: Scala 2.13.0 support

---

.travis.yml

Travis CI builds have been bitrotting on oraclejdk8 for some time.

openjdk8 and xenial

---

.travis.yml
build.sbt
project/Dependencies.scala
project/build.properties
sbt-java-gen/src/main/scala/Fs2GrpcServicePrinter.scala

- change usage of `raiseOrPure` to `liftTo` in
generated service definition.
- bump fs2, cats-effect and minitest
- bump scala 2.12.x
- bump sbt 1.3.0

all: move forward with dependencies

---

build.sbt

It no longer resolves, I suspect because of the sbt-1.3.0 upgrade.  I can't imagine anybody is using fs2-grpc and still on sbt-0.13.  If I'm wrong, a PR is welcome.  It's probably just adding back a resolver or something.

Drop sbt-0.13 support

---

.scala-steward.conf
project/Dependencies.scala

- revert sbt-protoc to 0.99.25 as 0.99.26 introduces
changes to default settings and that breaks out of
the box `.enablePlugins(Fs2Grpc)` behavior.
- add scala steward config that ignores sbt-protoc
until a solution is found.

revert: sbt-protoc as it changes defaults.

---

.scala-steward.conf
project/Dependencies.scala
sbt-java-gen/src/main/scala/Fs2GrpcPlugin.scala

- change scope of `PB.targets` setting to `Compile`
as sbt-protoc 0.99.26 introduces changes in its
default settings wrt. `PB.targets`. That breaks
the out of the box `.enablePlugins(Fs2Grpc)`
behavior.
- remove scala-steward.conf and move to 0.99.26

plugin: adjust to sbt-protoc changed its defaults

---

java-runtime/src/main/scala/client/Fs2ClientCall.scala
java-runtime/src/test/scala/client/ClientSuite.scala
sbt-java-gen/src/main/scala/Fs2GrpcServicePrinter.scala

- add ability for clients to adapt status runtime exceptions
sent from server side.

add ability to adapt status runtime exceptions

---

.scalafmt.conf
.travis.yml
build.sbt
project/Dependencies.scala

- remove support from Scala 2.11 as most of upstream
is doing that.
- set Scala 2.13.x as default for `ThisBuild` and use
2.12.10 for plugin.

deps: remove 2.11 + bump fs2 + 2.13 default

---

project/Dependencies.scala
project/plugins.sbt
sbt-java-gen/src/main/scala/Fs2GrpcServicePrinter.scala

- bump ScalaPB to 0.10.1 and adjust codegen
a bit with respect to method naming and 
fix deprecations.
- formatting is scalafmt

Upgrade to ScalaPB 0.10.1

---

build.sbt
project/Dependencies.scala
sbt-java-gen/src/main/scala/Fs2GrpcPlugin.scala

- change plugin to use grpc version from build-info
and use organization from build-info instead in order
to make it possible to use a different organization
in build.
- change dependency on grpc for runtime to only rely
on grpc-api as grpc-core is not needed.

only rely on grpc-api + prepare for controlling grpc version

---

project/plugins.sbt

Shouldn't be necessary in modern SBT, and is generating Scala Steward noise.
Replaces #230.

Remove sbt-coursier

---

java-gen/src/main/scala/Fs2GrpcServicePrinter.scala
java-runtime/src/main/scala/GeneratedCompanion.scala

- simplify code generation and use `GeneratedCompanion` for
convenience constructors.

gen/runtime: reduce code generation code

---

build.sbt
e2e/src/main/protobuf/package.proto
e2e/src/main/protobuf/test.proto
e2e/src/main/protobuf/test_service.proto
e2e/src/test/resources/TestServiceFs2Grpc.scala.txt
e2e/src/test/scala/io/fs2/grpc/CodegenSpec.scala
java-gen/src/main/scala/Fs2CodeGenerator.scala
project/Dependencies.scala
project/plugins.sbt

- define test for generated code.
- bump scalapb to 10.9 and fix deprecation warning
wrt. `ScalaPb` object moved to `scalapb.options`.

build: add e2e project for codegen verification

---

java-runtime/src/main/scala/client/Fs2StreamClientCallListener.scala
java-runtime/src/main/scala/server/Fs2StreamServerCallListener.scala
java-runtime/src/main/scala/syntax/ManagedChannelBuilderSyntax.scala
java-runtime/src/main/scala/syntax/ServerBuilderSyntax.scala
project/Dependencies.scala

- use `cats.effect.std.Queue` as
`fs.concurrent.std.Queue` is deprecated.
- `Stream.resource` requires `MonadCancel` now,
using `Async` instead of `Sync`.

deps: move ce/fs2 forward

---

java-runtime/src/main/scala/client/Fs2ClientCall.scala
java-runtime/src/main/scala/syntax/ManagedChannelBuilderSyntax.scala
java-runtime/src/main/scala/syntax/ServerBuilderSyntax.scala

- rename `handleCallError` to `handleExitCase` and account
for invoking cancel in case of successful exit when using
stream client call listener.
- make `ManagedChannelBuilderSyntax` and `ServerBuilderSyntax`
use explicit type params instead of `[_]`.

java-runtime: handle exit case + syntax

---

java-gen/src/main/scala/Fs2CodeGenerator.scala
project/Dependencies.scala
project/plugins.sbt

@rossabaker This requires a v0.10.0 tag as ScalaPB 0.11.0 is a breaking change, and it seems logical to go with 0.10.0 here. All dependencies from here on are minor bumps in series/0.x. Would great to get a 0.10.0 version published :)
A v0.9.1 would probably be nice for https://github.com/fiadliel/fs2-grpc/pull/325

deps: upgrade to scalapb 0.11.0

---

.github/workflows/ci.yml
build.sbt

1. Add the check to tests, so we catch it before we burn tags
2. Bump the initial versions since the last two tags failed
I think this one will work, because we're not retagging a commit.  See https://github.com/djspiewak/sbt-spiewak/issues/50 for that tale of woe.

Fix MiMa check so we can publish

---

build.sbt
runtime/src/main/scala/client/Fs2ClientCall.scala
runtime/src/main/scala/client/Fs2StreamClientCallListener.scala
runtime/src/main/scala/client/Fs2UnaryClientCallListener.scala

We lose the nicer `apply` name, but don't have to make any exceptions.

Remove MiMa exceptions for call listeners

---

build.sbt
runtime/src/main/scala/client/Fs2ClientCall.scala
runtime/src/main/scala/client/Fs2StreamClientCallListener.scala
runtime/src/main/scala/client/Fs2UnaryClientCallListener.scala
runtime/src/test/scala/client/ClientSuite.scala

- only request for more messages when stream is being pulled instead
of unconditionally request for more through `onMessage`.
- current behavior causes heap to fill up and eventually cause
out of memory exceptions.
- add test that showcases we only request more messages when there
is a demand.
- make listener constructors private to client as there is no need
guarantee binary compat for implementation details.
- adjust mima to exclude checks for methods made internal.

runtime: stream client call listener back-pressure

---

build.sbt
codegen/src/main/scala/Fs2GrpcServicePrinter.scala
e2e/src/test/resources/TestServiceFs2Grpc.scala.txt
runtime/src/main/scala/GeneratedCompanion.scala
runtime/src/main/scala/client/ClientOptions.scala
runtime/src/main/scala/client/Fs2ClientCall.scala
runtime/src/main/scala/client/Fs2StreamClientCallListener.scala
runtime/src/main/scala/client/Fs2UnaryClientCallListener.scala
runtime/src/main/scala/client/StreamIngest.scala
runtime/src/test/scala/client/ClientSuite.scala
runtime/src/test/scala/client/StreamIngestSuite.scala

- introduce client options
- allow for prefetching messages 
- remove deprecated methods
@rossabaker The prefetching addition is an improvement in that this allows us to make one call to request, say, 1000 messages. My thinking is that further improvements can be done on the consumer side by using fs2 `groupWithin` or `prefetchN`.
This is a breaking change such that we can clean a bit up and polish the user API wrt. `ClientOptions`. I'll look into backporting to 0.x series without breaking changes if you think this PR is ok.

runtime/codegen: introduce client options + allow for prefetching

---

.github/workflows/ci.yml
build.sbt
project/Dependencies.scala
project/plugins.sbt

- sbt-spiewak depends on an outdated sbt-dotty version,
which is why it needs to be added here temporarily until
sbt-spiewak removes it.

build: Scala 3.0.0 final!

---

java-runtime/src/main/scala/client/Fs2ClientCall.scala
java-runtime/src/main/scala/client/Fs2StreamClientCallListener.scala
java-runtime/src/main/scala/client/Fs2UnaryClientCallListener.scala
java-runtime/src/main/scala/client/StreamIngest.scala
java-runtime/src/test/scala/client/ClientSuite.scala
java-runtime/src/test/scala/client/StreamIngestSuite.scala

Use same strategy as in main branch with regards to prefetching in `Fs2StreamClientCallListener`.
- difference is that one uses `CallOptions` to set
the value of `prefetchN`, e.g.
`callOptions.withOption(Fs2ClientCall.prefetchNKey, 10)`
This is done in order not to wrech too much havoc in the
public API and avoiding to touch the code generator.
- `Fs2StreamClientCallListener` now uses `StreamIngest` that
is similar to that in the main branch.

java-runtime: use same strategy as in main branch.

---

README.md
build.sbt
codegen/src/main/scala/Fs2GrpcServicePrinter.scala
e2e/src/test/resources/TestServiceFs2Grpc.scala.txt
runtime/src/main/scala/GeneratedCompanion.scala
runtime/src/main/scala/client/Fs2ClientCall.scala
runtime/src/main/scala/server/Fs2ServerCall.scala
runtime/src/main/scala/server/Fs2ServerCallHandler.scala
runtime/src/main/scala/server/Fs2StreamServerCallListener.scala
runtime/src/main/scala/server/Fs2UnaryServerCallListener.scala
runtime/src/main/scala/server/ServerCallOptions.scala
runtime/src/main/scala/server/ServerOptions.scala
runtime/src/test/scala/server/ServerSuite.scala

- add `ServerOptions` as a way to avoid breaking
API going forward using a builder class for options
when using `service` methods.

codegen/runtime: add server options - clean up API

---

README.md
runtime/src/main/scala/GeneratedCompanion.scala

- add overloads for methods in `GeneratedCompanion`
with respect to using defaults for `ClientOptions`
and `ServerOptions` - This makes it less convoluted
for users that do not need to configure options.
- adjust docs for simpler upfront setup.

runtime: overloads to generated companion / readme
